// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Guide: typeof import('./src/components/Guide/Guide.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    Tips: typeof import('./src/components/Tips/Tips.vue')['default']
    TipsCom: typeof import('./src/components/ExampleGlobal/Toast.vue')['default'];
    Toast: typeof import('./src/components/ExampleGlobal/Toast.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanSlider: typeof import('vant/es')['Slider']
  }
}

export {}
